import { Injectable } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Router } from '@angular/router';
import { Observable, BehaviorSubject, of } from 'rxjs';
import { map, catchError} from 'rxjs/operators';
import { CookieService } from 'ngx-cookie-service';

@Injectable({
  providedIn: 'root'
})
export class AuthService {
  private apiUrl = 'http://localhost:2400/api/v1/authentication'; // initiate backend API URL
  private token: string | null = null;
  private authStatusListener = new BehaviorSubject<boolean>(false);

  constructor(private http: HttpClient, private router: Router, private cookieService: CookieService) {}
  
  //gets token generated by system
  getToken() {
    return this.token;
  }
  
  //checks if user is logged into system
  getAuthStatusListener() {
    return this.authStatusListener.asObservable();
  }

  isAdmin(): boolean {
    // Implement your logic to check if the user is an admin
    const adminId = this.getAdminId();
    return !!adminId;
  }
  
  //Creates an account for user on platform
  registerUser(user: any): Observable<any> {
    return this.http.post(`${this.apiUrl}/register`, user).pipe(
      // Handling the successful response
      map((response: any) => {
        // Redirect to login page after successful registration
        this.router.navigate(['/login']);
        // Returning the response if needed
        return response;
      })
    );
  }
  //logs user into the system
  loginUser(user: any): Observable<any> {
    return this.http.post<{ token: string, customer_id: string }>(`${this.apiUrl}/login`, user)
      .pipe(
        map(response => {
          if (response && response.token && response.customer_id) {
            this.token = response.token; // Save the token
            this.saveCustomerId(response.customer_id); // Save the customer ID
            this.authStatusListener.next(true); // Update the auth status
            return response; // Return the response
          } else {
            throw new Error('Invalid response from server: token or customer_id is missing');
          }
        }),
        catchError(error => {
          throw new Error('Error occurred while logging in: ' + error.message);
        })
      );
  }
  

  saveCustomerId(customerId: string): void {
    // Save customer_id as a cookie or in local storage
    this.cookieService.set('customer_id', customerId);
    // can also use localStorage.setItem('customer_id', customerId);
  }

  getCustomerId(): string {
    // Retrieve customer_id from cookie or local storage
    return this.cookieService.get('customer_id');
    // can also use return localStorage.getItem('customer_id');
  }
  //retrieves customer_id from cookie, used in a certain code to curve string observable error
  getUserId(): Observable<string> {
    return of(this.cookieService.get('customer_id'));
  }
  
  //logs user out from system
  logout() {
    // Clear token from local storage
    localStorage.removeItem('token');

    // Clear customer ID from local storage
    localStorage.removeItem('customer_id');

    // Clear any other necessary state
    this.token = null;
    this.authStatusListener.next(false);
    
    // Redirect to the login page
    this.router.navigate(['/login']);
}

 // Admin Authentication, registers a new admin
 registerAdmin(admin: any): Observable<any> {
  return this.http.post(`${this.apiUrl}/register-admin`, admin).pipe(
    map((response: any) => {
      this.router.navigate(['/login-admin']);
      return response;
    })
  );
}
 // logs admin into the system
loginAdmin(admin: any): Observable<{ token: string, admin_id: string }> {
  return this.http.post<{ token: string, admin_id: string }>(`${this.apiUrl}/login-admin`, admin)
    .pipe(
      map(response => {
        if (response && response.token && response.admin_id) {
          this.token = response.token;
          this.saveAdminId(response.admin_id);
          this.authStatusListener.next(true);
          return response;
        } else {
          throw new Error('Invalid response from server: token or admin_id is missing');
        }
      }),
      catchError(error => {
        throw new Error('Error occurred while logging in: ' + error.message);
      })
    );
}

//After admin signs in, their id is saved to the cookie
saveAdminId(adminId: string): void {
  this.cookieService.set('admin_id', adminId);
}

//retrieves admin id from cookie
getAdminId(): Observable<string> {
  return of(this.cookieService.get('admin_id'));
}

//logs admin out of the system
logoutAdmin() {
  localStorage.removeItem('token');
  this.cookieService.delete('admin_id');
  this.token = null;
  this.authStatusListener.next(false);
  this.router.navigate(['/login-admin']);
}
  //Checks whether or not user is authenticated/logged in
  isAuthenticated(): boolean {
    return this.token !== null;
  }

   // updates admin password
   updateAdminPassword(id:number, data:any): Observable<any>{
    return this.http.patch<any>(this.apiUrl + `/update-password-admin/${id}`, data)
                                .pipe(
                                  map((res)=>{
                                    return res;
                                  }
                                  )
                                );
  }

  // updates customer password
  updatePassword(id:number, data:any): Observable<any>{
    return this.http.patch<any>(this.apiUrl + `/update-password/${id}`, data)
                                .pipe(
                                  map((res)=>{
                                    return res;
                                  }
                                  )
                                );
  }
}

